---
title: "COVID19"
subtitle: "Samfélagsleg viðbrögð og spálíkan fyrir Ísland"
date: "`r Sys.Date()`"
output: xaringan::moon_reader
---

```{r setup, context = "setup", include=FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, fig.asp = 0.621, out.width = "100%", fig.width = 8)

library(tidyverse); library(cowplot); library(kableExtra); library(scales); library(gganimate)
library(lubridate); library(emmeans); library(broom); 
theme_set(theme_classic(base_size = 12) + 
            background_grid(color.major = "grey90", 
                            color.minor = "grey95", 
                            minor = "xy", major = "xy") +
            theme(legend.position = "none"))
select <- dplyr::select
Sys.setlocale("LC_TIME", "is_IS")
```

```{r data, context = "data"}
d <- read_csv("Data/smit.csv") %>% 
  filter(tegund == "Samtals", fjoldi > 0)
aldur <- read_csv("Data/aldur.csv")
world_d <- read_csv("Data/ECDC_Data.csv") %>% 
  filter(case_rate > 0.0001) 
hubei_d <- read_csv("Data/Hubei_JHU_data.csv")


preds_cumulative <- read_csv("Data/preds_cumulative.csv")
preds_active <- read_csv("Data/preds_active.csv")
aldur <- read_csv("Data/aldur.csv")
simulations_cumulative <- read_csv("Data/simulations_cumulative.csv")
simulations_active <- read_csv("Data/simulations_active.csv")
```

```{r}
preds_active  %>% 
  mutate(dags = min(d$dags) + dagar - 3) %>% 
  ggplot(aes(dags, pred)) +
  geom_line() +
  geom_line(aes(y = upper), lty = 2) +
  geom_point(data = d, aes(dags, fjoldi)) +
  scale_y_continuous(breaks = pretty_breaks(8)) +
  scale_x_date(date_breaks = "2 weeks", date_labels = "%d/%m") +
  labs(title = "Virk smit í heildina") +
  theme(axis.title = element_blank())
```

--- 

# Aðferð


Texti



---

```{r, fig.asp = 1}
simulations_active %>% 
  filter(variable == "cases") %>% 
  ggplot(aes(dags, median)) +
  geom_line() +
  geom_line(aes(y = upper), lty = 2) +
  facet_wrap("aldur", scales = "free") +
  scale_y_continuous(breaks = pretty_breaks(8)) +
  scale_x_date(date_breaks = "1 month", date_labels = "%d/%m") +
  labs(title = "Virk smit eftir aldri",
       y = "Tilfelli") +
  theme(axis.title = element_blank())
```

