---
title: "Logistic"
author: "Brynjólfur Gauti Jónsson"
date: "3/17/2020"
output: 
    html_document:
        theme: flatly
        code_folding: hide
runtime: shiny_prerendered
---

```{r setup, context = "setup", include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, 
                      fig.asp = 0.621, out.width = "100%", fig.width = 8)

library(tidyverse); library(knitr); library(kableExtra); library(broom); library(cowplot); 
library(rstan); library(tidybayes); library(scales)

theme_set(theme_classic(base_size = 12) + 
            background_grid(color.major = "grey90", 
                            color.minor = "grey95", 
                            minor = "xy", major = "xy") +
            theme(legend.position = "none"))
options(mc.cores = parallel::detectCores())
```


# Gögn

## Lönd

```{r, context = "data"}
d <- read_csv("https://www.dropbox.com/s/rn1p592hjazvra6/stan_dat.csv?dl=1") %>% 
  arrange(country)
m <- read_rds("Hierarchical_Logistic_Rates.rds")
```


Hvaða lönd eru notuð?

* Ef meri en 10 dagar eru síðan tíðni per 1000 fór yfir 0.01
* Ekki Kína í heild og heldur ekki Hubei

```{r}
d %>% 
  group_by(country) %>% 
  summarise(First = min(date),
            Days_In_Data = n(),
            Start_Rate = min(case_rate),
            End_Rate = max(case_rate)) %>% 
  kable %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```

## Breytur

```{r}
N_obs <- nrow(d)
N_countries <- max(d$country_id)
max_case_rate <- 1000


days <- d$days
case_rate <- d$case_rate
cases <- d$cases
country <- d$country_id %>% as.integer


pop <- d %>% distinct(country_id, pop) %>% arrange(country_id) %>%  .$pop
pop <- pop / 1000

country_max <- d %>% 
  group_by(country_id) %>% 
  summarise(maximum = max(case_rate)) %>% 
  arrange(country_id) %>% 
  .$maximum


stan_data <- list(N_obs = N_obs, N_countries = N_countries, max_case_rate = max_case_rate,
                  days = days, obs_case_rate = case_rate, obs_cases = cases, country = country,
                  pop = pop, country_max = country_max)
```

```{r}
str(stan_data)
```

```{r, eval = F}
m <- sampling(stan_model("Logistic_case_rate_reverse.stan"), 
              data  = stan_data, chains = 4, iter = 2000, warmup = 1000)
```

```{r, context = "render"}
selectInput(inputId = "country",
            label = "Land",
            choices = unique(d$country), selected = "Iceland")
numericInput(inputId = "conf",
             label = "Öryggismörk", min = 0.01, max = 0.99, value = 0.95, step = 0.01)

plotOutput("pred_plot")
```


```{r, context = "server"}
output$pred_plot <- renderPlot({
  
  req(input$country, input$conf)
  
  plot_dat <- d %>% filter(country == input$country)
  country_id = unique(plot_dat$country_id)
  chosen_country <- country_id
  population <- max(plot_dat$pop) / 1000
  alph <- 1 - input$conf
  
  results <- spread_draws(m, 
                          alpha[country_id],
                          beta[country_id], 
                          maximum[country_id],
                          sigma_sq_obs[country_id]) %>% 
    filter(country_id == chosen_country) %>% 
    distinct(alpha, beta, maximum, sigma_sq_obs) %>% 
    mutate(iter = row_number()) %>% 
    expand_grid(days = seq(-10, 50)) %>% 
    mutate(linear = alpha + beta * days,
           rate = maximum / (1 + exp(-linear)),
           rate = rnorm(n(), rate, sigma_sq_obs),
           cases = rate * population)
  
  br <- pretty_breaks(6)(results$rate)
  br <- br[br >= 0]
  case_br <- br * population
  
  plot_lab1 <- str_c("Uppsöfnuð smit í ", 
                     input$country, 
                     ": Spá og raun")
  
  p1 <- results %>% 
    mutate(date = days + min(plot_dat$date)) %>% 
    group_by(date) %>% 
    summarise(median = median(rate),
              lower = quantile(rate, alph / 2),
              upper = quantile(rate, 1 - alph / 2)) %>% 
    ggplot(aes(date, median, ymin = lower, ymax = upper)) +
    geom_line(aes(y = lower), lty = 2) +
    geom_line(aes(y = upper), lty = 2) +
    geom_line() +
    geom_point(data = plot_dat,
               aes(date, case_rate), inherit.aes = F) +
    scale_y_continuous(breaks = br,
                       sec.axis = sec_axis(trans = ~. * population, 
                                           name = "Fjöldi smita",
                                           breaks = case_br,
                                           labels = function(x) round(x, -2))) +
    labs(y = "Tíðni smita (per 1000 íbúar)",
         title = plot_lab1,
         subtitle = "Forspáð miðgildi ásamt 95% PI") +
    theme(axis.title.x = element_blank())
  
  
  results <- results %>% 
    group_by(iter) %>% 
    mutate(rate = rate - lag(rate, 21, default = 0),
           cases = cases - lag(cases, 21, default = 0)) %>% 
    ungroup
  
  br <- pretty_breaks(6)(results$rate)
  br <- br[br >= 0]
  case_br <- br * population
  
  plot_lab2 <- str_c("Virk smit í ", 
                     input$country, 
                     ": Spá og raun")
  p2 <- results %>% 
    mutate(date = days + min(plot_dat$date)) %>% 
    group_by(date) %>% 
    summarise(median = median(rate),
              lower = quantile(rate, alph / 2),
              upper = quantile(rate, 1 - alph / 2)) %>% 
    ggplot(aes(date, median, ymin = lower, ymax = upper)) +
    geom_line(aes(y = lower), lty = 2) +
    geom_line(aes(y = upper), lty = 2) +
    geom_line() +
    geom_point(data = plot_dat,
               aes(date, case_rate), inherit.aes = F) +
    scale_y_continuous(breaks = br,
                       sec.axis = sec_axis(trans = ~. * population, 
                                           name = "Fjöldi smita",
                                           breaks = case_br,
                                           labels = function(x) round(x, -2))) +
    labs(y = "Tíðni smita (per 1000 íbúar)",
         title = plot_lab2,
         subtitle = "Forspáð miðgildi ásamt 95% PI") +
    theme(axis.title.x = element_blank())
  
  plot_grid(p1, p2, align = "v")
})
```

# Líkan (Stan kóði)

```{r, eval = FALSE}
data {
  int<lower = 0> N_obs;
  vector[N_obs] case_rate;
  vector[N_obs] days;
  int country[N_obs];
  int cases[N_obs];
  
  
  int<lower = 0> N_countries;
  vector[N_countries] pop;
  vector[N_countries] country_max;
  int<lower = 0> max_case_rate;
}

parameters {
  vector[N_countries] beta;
  vector[N_countries] alpha;
  vector<lower = 0, upper = 1>[N_countries] maximum_pre;
  
  real mu_beta;
  real<lower = 0> sigma_sq_beta;
  
  real mu_alpha;
  real<lower = 0> sigma_sq_alpha;
  
  vector<lower = 0>[N_countries] sigma_sq_obs;
  real<lower = 0> a_sigma_obs;
  real<lower = 0> b_sigma_obs;
  
  real<lower = 0> beta_a;
  real<lower = 0> beta_b;
}

transformed parameters {
  vector[N_countries] maximum = maximum_pre * max_case_rate;
  vector[N_obs] linear = alpha[country] + beta[country] .* days;
  vector<lower = 0, upper = 1000>[N_obs] true_rate;
  for (i in 1:N_obs) true_rate[i] = maximum[country[i]] .* 1 / (1 + exp(-linear[i]));
}

model {
  sigma_sq_beta ~ inv_chi_square(1);
  sigma_sq_alpha ~ inv_chi_square(1);
  sigma_sq_obs ~ inv_gamma(a_sigma_obs, b_sigma_obs);
  
  maximum_pre ~ beta(beta_a, beta_b);
  
  beta ~ normal(mu_beta, sigma_sq_beta);
  alpha ~ normal(mu_alpha, sigma_sq_alpha);
  
  
  case_rate ~ normal(true_rate, sigma_sq_obs[country]);
  
}
```

