---
title: "Logistic"
author: "Brynjólfur Gauti Jónsson"
date: "3/17/2020"
output: 
    html_document:
        theme: flatly
        code_folding: hide
---

```{r setup, context = "setup", include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, 
                      fig.asp = 0.621, out.width = "100%", fig.width = 8)

library(tidyverse); library(knitr); library(kableExtra); library(broom); library(cowplot); 
library(rstan); library(tidybayes); library(scales); library(shinystan)

theme_set(theme_classic(base_size = 12) + 
            background_grid(color.major = "grey90", 
                            color.minor = "grey95", 
                            minor = "xy", major = "xy") +
            theme(legend.position = "none"))
options(mc.cores = parallel::detectCores())
```


# Gögn

## Lönd

```{r}
d <- read_csv("stan_dat.csv")
aldur <- read_csv("../../Data/aldur.csv")

d %>% 
  group_by(country) %>% 
  summarise(First = min(date),
            Last = max(date),
            Days_In_Data = n(),
            Start_Rate = min(case_rate),
            End_Rate = max(case_rate),
            Pop = unique(pop)) %>% 
  kable %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
```


## Breytur

```{r}
N_obs <- nrow(d)
N_countries <- max(d$country_id)


days <- d$days
cases <- d$cases
country <- d$country_id %>% as.integer


pop <- d %>% distinct(country_id, pop) %>% arrange(country_id) %>%  .$pop
pop <- pop

iceland_d <- d %>% filter(country == "Iceland")

iceland_id <- unique(iceland_d$country_id)
N_preds <- 60
N_agegroups <- 9
pred_days <- seq_len(N_preds) - 1
age_dist <- aldur$p_tilfelli
hospital_dist <- aldur$p_spitali
icu_dist <- aldur$p_alvarlegt

stan_data <- list(N_obs = N_obs,
                  N_countries = N_countries,
                  days = days, 
                  obs_cases = cases, 
                  country = country,
                  pop = pop)
```

```{r}
str(stan_data)
```


```{r, eval = F}
m <- sampling(stan_model("Hierarchical_Logistic_Cases.stan"), 
              data  = stan_data, chains = 4, iter = 3000, warmup = 1000,
              control = list(max_treedepth = 15))

# write_rds(m, "Hierarchical_Logistic_Rates.rds")
```

```{r}
tidyMCMC(m, conf.int = T, rhat = T, ess = T)
```


```{r}
input <- list(country = "Iceland")
plot_dat <- d %>% filter(country == input$country)
country_id = unique(plot_dat$country_id)
chosen_country <- country_id
results <- spread_draws(m, 
                        alpha[country_id],
                        beta[country_id], 
                        maximum[country_id]) %>% 
  ungroup %>% 
  filter(country_id == chosen_country) %>% 
  distinct(alpha, beta, maximum) %>% 
  mutate(iter = row_number()) %>% 
  expand_grid(days = seq(0, 60)) %>% 
  mutate(linear = alpha + beta * days,
         rate = maximum / (1 + exp(-linear)),
         cases = rpois(n(), lambda = rate * 364260)) %>% 
  group_by(days) %>% 
  summarise(median = median(cases),
            upper = quantile(cases, 0.975),
            lower = quantile(cases, 0.025)) %>% 
  mutate(date = days + min(plot_dat$date))

p_cumul <- results %>% 
  ggplot(aes(date, median, ymin = lower, ymax = upper)) +
  geom_line(aes(y = lower), lty = 2) +
  geom_line(aes(y = upper), lty = 2) +
  geom_line() +
  geom_point(data = plot_dat,
             aes(date, cases), inherit.aes = F) +
  scale_y_continuous(breaks = pretty_breaks(10)) +
  theme(axis.title.x = element_blank())
p_cumul +
  ggsave("uppsöfnuð_smit.png")
```

```{r}
input <- list(country = "Iceland")
plot_dat <- d %>% filter(country == input$country)
country_id = unique(plot_dat$country_id)
chosen_country <- country_id
results <- spread_draws(m, 
                        alpha[country_id],
                        beta[country_id], 
                        maximum[country_id]) %>% 
  ungroup %>% 
  filter(country_id == chosen_country) %>% 
  distinct(alpha, beta, maximum) %>% 
  mutate(iter = row_number()) %>% 
  expand_grid(days = seq(0, 60)) %>% 
  mutate(linear = alpha + beta * days,
         rate = maximum / (1 + exp(-linear)),
         cases = rpois(n(), lambda = rate * 364260)) %>% 
  group_by(iter) %>% 
  mutate(cases = cases - lag(cases, n = 21, default = 0)) %>% 
  group_by(days) %>% 
  summarise(median = median(cases),
            upper = quantile(cases, 0.975),
            lower = quantile(cases, 0.025)) %>% 
  mutate(date = days + min(plot_dat$date))

p_active <- results %>% 
  ggplot(aes(date, median, ymin = lower, ymax = upper)) +
  geom_line(aes(y = lower), lty = 2) +
  geom_line(aes(y = upper), lty = 2) +
  geom_line() +
  geom_point(data = plot_dat,
             aes(date, cases), inherit.aes = F) +
  theme(axis.title.x = element_blank())

p_active +
  ggsave("active_smit.png")
```

```{r}
spread_draws(m, pred_cumul_cases[day]) %>% 
  group_by(day) %>% 
  summarise(median = median(pred_cumul_cases),
            upper = quantile(pred_cumul_cases, 0.99)) %>% 
  ungroup %>% 
  mutate(day = day - 1,
         date = min(iceland_d$date) + day + min(pred_days)) %>% 
  ggplot(aes(date, median)) +
  geom_line() +
  geom_line(aes(date, upper), lty = 2) +
  geom_point(data = iceland_d, aes(date, cases))
```


# Herma

## Aldursdreifing

```{r}
age_preds <- spread_draws(m, pred_cumul_agegroups[day, age]) %>% 
  group_by(day, age) %>% 
  summarise(median = median(pred_cumul_agegroups),
            upper = quantile(pred_cumul_agegroups, 0.99)) %>% 
  ungroup %>% 
  mutate(day = day - 1,
         date = min(iceland_d$date) + day + min(pred_days),
         age = 10 * (age  - 1),
         age = str_c("[", age, " - ", age + 9, "]"))

age_preds %>% 
  ggplot(aes(date, median)) +
  geom_line() +
  geom_line(aes(y = upper))+ 
  facet_wrap("age", scales = "free")
```


## Spítali

```{r}
hosp_preds <- spread_draws(m, pred_cumul_hospital[day, age]) %>% 
  group_by(day, .iteration, .chain) %>% 
  summarise(total = sum(pred_cumul_hospital)) %>% 
  group_by(day) %>% 
  summarise(median = median(total),
            upper = quantile(total, .99)) %>% 
  mutate(day = day - 1,
         date = min(iceland_d$date) + day + min(pred_days))

hosp_preds %>% 
  ggplot(aes(date, median)) +
  geom_line() +
  geom_line(aes(y = upper), lty = 2) +
  ggsave("hospital_preds.png")
```

## Gjörgæsla

```{r}
icu_preds <- spread_draws(m, pred_cumul_icu[day, age]) %>% 
  group_by(day, .iteration, .chain) %>% 
  summarise(total = sum(pred_cumul_icu)) %>% 
  group_by(day) %>% 
  summarise(median = median(total),
            upper = quantile(total, .99)) %>% 
  mutate(day = day - 1,
         date = min(iceland_d$date) + day + min(pred_days))

icu_preds %>% 
  ggplot(aes(date, median)) +
  geom_line() +
  geom_line(aes(y = upper), lty = 2) +
  ggsave("icu_preds.png")
```

```{r}
res <- spread_draws(m, pred_cumul_cases[day])

res <- res %>% 
  ungroup %>% 
  select(.chain, .iteration, day, cumulative_cases = pred_cumul_cases) %>% 
  arrange(.chain, .iteration, day) %>% 
  group_by(.chain, .iteration) %>% 
  mutate(recovered_cases = lag(cumulative_cases, n = 21, default = 0),
         active_cases = pmax(0, cumulative_cases - recovered_cases)) %>% 
  select(-cumulative_cases, -recovered_cases)

res <- res %>% 
  rowwise %>% 
  mutate(age_cases = list(tibble(age = aldur$aldur, age_cases = rmultinom(1, active_cases, aldur$p_tilfelli)))) %>% 
  ungroup %>% 
  unnest
```

