---
title: "Modeling"
author: "Brynjólfur Gauti Jónsson"
date: "3/15/2020"
output: 
    html_document:
        theme: flaty
        code_folding: hide
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width = 8, fig.asp = 0.621, out.width = "100%")
```

# Packages

```{r}
packages <- c("tidyverse", "knitr", "kableExtra", "broom",
              "cowplot", "rstan", "tidybayes", "scales", 
              "lubridate")
sapply(packages, require, character.only = TRUE, quietly = TRUE)
theme_set(theme_bw() + 
              panel_border(colour = "grey30", size = 1) + 
              background_grid(color.major = "grey90", 
                              color.minor = "grey95", 
                              minor = "xy", major = "xy"))
rm(packages)
options(mc.cores = parallel::detectCores())
```

```{r}
d <- read_csv("https://raw.githubusercontent.com/bgautijonsson/covid19/master/Input/ECDC_Data.csv") %>% 
    group_by(country) %>% 
    mutate(infected = lag(total_cases, 1, default = 0),
           susceptible = pop - infected) %>% 
    filter(case_rate >= 0.04, continent == "Europe") %>% 
    group_by(country) %>% 
    filter(n() > 10) %>% 
    mutate(days = row_number() - 1) %>% 
    ungroup %>% 
    mutate(country_id = as.numeric(as.factor(country))) %>% 
    select(country, country_id, days, new_cases, 
           infected, susceptible, pop)

d
```

```{r}
N_obs <- nrow(d)
N_countries <- length(unique(d$country))

I <- d$infected
S <- d$susceptible
N <- d$pop

I_N <- I / N
new_cases <- d$new_cases
country <- d$country_id

stan_data <- list(
    N_obs = N_obs, 
    N_countries = N_countries,
    I = I, S = S, new_cases = new_cases, I_N = I_N,
    country = as.integer(country)
    )
str(stan_data)
```


```{r}
m <- sampling(stan_model("Chain_Binomial.stan"), 
              data  = stan_data, chains = 4, iter = 2000, warmup = 1000)
```


```{r}
tidyMCMC(m, conf.int = T, rhat = T, ess = T)
```

