---
title: "Fyrsta forspá um fjölda tilfella og álag á Landspítali"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
runtime: shiny_prerendered
---

```{r setup, context = "setup", include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, fig.align = "center",
                      fig.asp = 0.621, out.width = "100%", fig.width = 7)
library(tidyverse); library(cowplot); library(kableExtra); library(scales); library(gganimate)
library(lubridate); library(emmeans); library(broom); library(propagate)
theme_set(theme_classic(base_size = 12) + 
            background_grid(color.major = "grey90", 
                            color.minor = "grey95", 
                            minor = "xy", major = "xy") +
            theme(legend.position = "none"))
select <- dplyr::select
```

```{r data, context = "data", include = FALSE}
world_d <- read_csv("../../Data/ECDC_Data.csv") %>% 
  filter(case_rate > 0.0001) %>% 
  filter(country %in% c("South Korea", "Italy")) %>% 
  bind_rows(read_csv("../../Data/Hubei_JHU_Data.csv"))

preds <- read_csv("preds.csv")

preds_active <- preds %>% 
  pivot_longer(-dagar) %>% 
  arrange(dagar, name) %>% 
  group_by(name) %>% 
  mutate(lag_value = lag(value, n = 21, default = 0)) %>% 
  ungroup %>% 
  mutate(value = value - lag_value) %>% 
  select(-lag_value) %>% 
  pivot_wider() 

d <- read_csv("smit.csv") %>% 
  filter(tegund == "Samtals", fjoldi > 0)
```

# Lógístískur vöxtur

## Heimurinn

```{r, fig.align='center'}
selectInput(inputId = "country", label = "Land",
            choices = unique(world_d$country),
            selected = "Hubei")
```

```{r}
plotOutput("sslogis")
```



```{r, context = "server"}
output$sslogis <- renderPlot({
  model_d <- world_d %>% filter(country == input$country)
  
  m <- nls(cum_cases ~ SSlogis(days, phi1, phi2, phi3), data = model_d)
  
  pred_d <- predict(m, newdata = tibble(days = seq(min(model_d$days), pmax(70, max(model_d$days))))) %>% 
    as_tibble %>% 
    mutate(days = row_number() - 1 + min(model_d$days)) %>% 
    mutate(date = days + min(model_d$date) - min(days),
           active = value - lag(value, 21, default = 0))
  
  model_d %>% 
    ggplot() +
    geom_line(data = pred_d, aes(x = date, y = value)) +
    geom_point(aes(date, cum_cases)) +
    labs(title = "Líkanið fellur vel að gögnum Í Hubei héraði í Kína",
         x = "Dagsetning", y = "Fjöldi tilfella")
})
```

## Ísland

```{r}
selectInput(inputId = "iceland_type",
            label = "Tegund forspár",
            choices = c("Uppsöfnuð smit", "Virk smit"),
            selected = "Uppsöfnuð smit")
plotOutput("iceland_plot")
```


```{r, context = "server"}
output$iceland_plot <- renderPlot({
  if (input$iceland_type == "Uppsöfnuð smit") {
    preds  %>% 
      mutate(dags = min(d$dags) + dagar -1) %>% 
      ggplot(aes(dags, pred)) +
      geom_line() +
      geom_line(aes(y = upper), lty = 2) +
      geom_point(data = d, aes(dags, fjoldi)) +
      labs(title = "Forspáð þróun í uppsöfnuðum smitafjölda",
           subtitle = "Besta mat (llína) auk efri marka (brotin lína)") +
      theme(axis.title = element_blank())
  } else {
    preds_active  %>% 
      mutate(dags = min(d$dags) + dagar -1) %>% 
      ggplot(aes(dags, pred)) +
      geom_line() +
      geom_line(aes(y = upper), lty = 2) +
      geom_point(data = d, aes(dags, fjoldi)) +
      labs(title = "Forspáð þróun fjölda smita hverju sinni",
           subtitle = "Miðað við að einstaklingur hefur jafnað sig þremur vikum eftir greiningu") +
      theme(axis.title = element_blank())
  }
})
```

