---
title: "Logistic Growth Curves"
author: "Brynjólfur Gauti Jónsson"
date: "3/28/2020"
output: 
    html_document:
        theme: flatly
        toc: true
        toc_float: true
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, 
                      fig.asp = 0.621, out.width = "100%", fig.width = 8)
```

```{r}
library(tidyverse); library(knitr); library(kableExtra); library(broom); library(cowplot); 
library(rstan); library(tidybayes); library(scales)
library(lubridate)



d <- read_csv("https://docs.google.com/spreadsheets/d/1ODqwILD6yBfE5mgKmI4mE-t-wzBDaw8l27gERUiAMgo/export?format=csv&gid=0") %>% 
    rename(new_deaths = "Dauðsföll") %>% 
    mutate(ny_smit = Ny_Smit + IE_Smit,
           date = mdy(Dagsetning),
           total_deaths = cumsum(new_deaths),
           country = "Iceland") %>% 
    select(country, date, total_cases = Smit_Samtals, new_cases = ny_smit, new_deaths, total_deaths) %>% 
    filter(date >= ymd("2020-03-05")) %>% 
    mutate(days = row_number() - 1)

```


```{r}
N_obs <- nrow(d)
N_preds <- 80
pred_days <- seq_len(N_preds) - 1
days <- d$days
new_cases <- d$new_cases
pop <- 364260

stan_data <- list(
    N_obs = N_obs,
    N_preds = N_preds,
    pred_days = pred_days,
    days = days,
    new_cases = new_cases,
    pop = pop
)
```


```{r}
m <- sampling(stan_model("Hierarchical_Logistic_Cases_NegBin_Iceland.stan"), 
              data  = stan_data, chains = 4, iter = 2000, warmup = 1000)
```


```{r}
tidyMCMC(m, pars = "beta", rhat = T, ess = T, conf.int = T) %>% 
    mutate(days = row_number() - 1) %>% 
    ggplot(aes(days, estimate, ymin = conf.low, ymax = conf.high)) +
    geom_ribbon(alpha = 0.2) +
    geom_line()
```


```{r}
spread_draws(m, pred_cases[days]) %>% 
    ungroup %>% 
    select(days, pred_cases) %>% 
    group_by(days) %>% 
    mutate(iter = row_number()) %>% 
    group_by(iter) %>% 
    mutate(total_cases = cumsum(pred_cases)) %>% 
    group_by(days) %>% 
    summarise(median = median(total_cases),
              upper = quantile(total_cases, .975)) %>% 
    ggplot(aes(days, median)) +
    geom_line() +
    geom_line(aes(y = upper), lty = 2)
```


