---
title: "Modeling"
author: "Brynjólfur Gauti Jónsson"
date: "3/15/2020"
output: 
    html_document:
        theme: flaty
        code_folding: hide
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width = 8, fig.asp = 0.621, out.width = "100%")
```

```{r}
library(tidyverse); library(knitr); library(kableExtra); library(broom); library(cowplot); 
library(rstan); library(tidybayes); library(scales)
library(lubridate); library(ggtext)
theme_set(theme_bw() + 
              panel_border(colour = "grey30", size = 1) + 
              background_grid(color.major = "grey90", 
                              color.minor = "grey95", 
                              minor = "xy", major = "xy"))
options(mc.cores = parallel::detectCores())


d <- read_csv("https://docs.google.com/spreadsheets/d/1xgDhtejTtcyy6EN5dbDp5W3TeJhKFRRgm6Xk0s0YFeA/export?format=csv&id=1xgDhtejTtcyy6EN5dbDp5W3TeJhKFRRgm6Xk0s0YFeA&gid=1788393542") %>% 
    select(
        date = "Dagsetning",
        new_cases = "Ny_Smit",
        new_deaths = "Dauðsföll",
        new_recovered = "Batnað", 
        total_cases = "Smit_Samtals",
        total_deaths = "Dauðsföll_Samtals",
        total_recovered = "Batnað_Samtals",
        total_removed = "Removed_Samtals",
        active_cases = "Virk_Smit",
        perc_positive = "IE_Hlutf_Jakvaett") %>% 
    filter(perc_positive > 0)

d
```


```{r}
N_days <- nrow(d)
days <- seq_len(N_days) - 1

perc_positive <- d$perc_positive

stan_data <- list(
    N_days = N_days,
    days = days,
    perc_positive = perc_positive
)

str(stan_data)
```


```{r}
m <- sampling(stan_model("Prevalence.stan"), 
              data  = stan_data, chains = 4, iter = 2000, warmup = 1000)
```
