---
title: "Slembiþáttalíkan fyrir NegBinomial dreifð tilfelli"
author: "Brynjólfur Gauti Jónsson"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: flatly
  pdf_document: default
subtitle: Metið fyrir öll lönd heims
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width = 8, fig.asp = 0.621, out.width = "100%")
```

```{r}
packages <- c("tidyverse", "knitr", "kableExtra", "broom", "cowplot", "rstan", "tidybayes", "scales", "ggridges", "lubridate")
installed <- sapply(packages, require, character.only = TRUE, quietly = TRUE)
theme_set(theme_classic(base_size = 12) + 
              background_grid(color.major = "grey90", 
                              color.minor = "grey95", 
                              minor = "xy", major = "xy") +
              theme(legend.position = "none"))
rm(packages, installed)
options(mc.cores = parallel::detectCores())
```


```{r}
d <- read_csv("../Data/ECDC_Data.csv") %>% 
    filter(date >= ymd("2020-03-02")) %>%
    # filter(continent %in% "Europe") %>% 
    select(country, pop, date, days, cases = cum_cases, case_rate) %>% 
    group_by(country) %>% 
    mutate(days = row_number() - 1) %>% 
    ungroup %>% 
    mutate(country_id = as.numeric(as.factor(country)))
```

```{r}
d %>% 
    ggplot(aes(date, case_rate, group = country, col = country == "Iceland")) +
    geom_line() +
    scale_y_log10() +
    scale_colour_manual(values = c("grey", "blue")) +
    theme(legend.position = "none",
          axis.title.x = element_blank()) +
    labs(title = "Smitfjöldaþróun í heiminum",
         susbtitle = "Ísland byrjar með mikla tíðni á höfðatöu en hún eykst hægt",
         y = "Tíðni tilfella per 1000 íbúa")
```


```{r}
N_obs <- nrow(d)
N_countries <- max(d$country_id)
days <- d$days
cases <- d$cases %>% as.integer
country <- d$country_id %>% as.integer
pop <- d %>% distinct(country_id, pop) %>% .$pop / 1000
stan_data <- list(N_obs = N_obs, N_countries = N_countries, days = days, cases = cases, country = country, pop = pop)
```


```{r}
if (!file.exists("NegBin_Hierarchical.rds")) {
    m <- sampling(stan_model("NegBin_Hierarchical.stan"), 
                  data  = stan_data, chains = 8, iter = 2000, warmup = 500)
    write_rds(m, "NegBin_Hierarchical.rds")
} else {
    m <- read_rds("NegBin_Hierarchical.rds")
}
```

```{r, fig.asp = 1.5, fig.width = 10}
tidyMCMC(m, pars = c("alpha", "beta"), conf.int = T, ess = T, rhat = T) %>% 
    mutate(par = str_extract(term, "^alpha|beta")) %>%
    filter(par == "beta") %>% 
    group_by(par) %>% 
    mutate(country_id = row_number()) %>% 
    inner_join(
        d %>% distinct(country, country_id)
    ) %>% 
    select(country, par, estimate, conf.low, conf.high) %>% 
    mutate(country = fct_reorder(country, estimate)) %>% 
    mutate_at(vars(estimate, contains("conf")), ~ exp(.) - 1) %>% 
    ggplot(aes(country, estimate, ymin = conf.low, ymax = conf.high, col = country == "Iceland")) +
    geom_linerange() +
    geom_point() +
    scale_y_continuous(labels = percent) +
    scale_colour_manual(values = c("grey", "blue")) +
    coord_flip() +
    theme(axis.title = element_blank(), legend.position = "none") +
    labs(title = "Dagleg aukning tilfella á höfðatölu",
         subtitle = "Ísland er mjög neðarlega")
```

