---
title: "Modeling"
author: "Brynjólfur Gauti Jónsson"
date: "3/15/2020"
output: 
    html_document:
        theme: flaty
        code_folding: hide
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.width = 8, fig.asp = 0.621, out.width = "100%")
```

# Packages

```{r}
packages <- c("tidyverse", "knitr", "kableExtra", "broom", "cowplot", "rstan", "tidybayes", "scales", 
              "lubridate")
sapply(packages, require, character.only = TRUE, quietly = TRUE)
theme_set(theme_bw() + 
              panel_border(colour = "grey30", size = 1) + 
              background_grid(color.major = "grey90", 
                              color.minor = "grey95", 
                              minor = "xy", major = "xy"))
rm(packages)
options(mc.cores = parallel::detectCores())
```

```{r}
countries <- c("Iceland", "Norway", "Sweden", "Denmark", "Italy", "Spain", "Germany", "United States", "South Korea",
               "United Kingdom", "Austria", "Switzerland", "Belgium", "France", "Singapore", "Japan", "Canada")
d <- read_csv("https://raw.githubusercontent.com/bgautijonsson/covid19/master/Input/ECDC_Data.csv") %>% 
    select(country, date, total_cases, pop) %>% 
    mutate(date = date + (country == "Iceland"),
           total_cases = as.integer(total_cases)) %>% 
    filter(date >= ymd("2020-03-02"), 
           country %in% countries)

d
```


```{r}
total_cases <- d %>% 
    select(-pop) %>% 
    spread(country, total_cases) %>% 
    select(-date) %>% 
    as.matrix

N_days <- nrow(total_cases)
N_countries <- ncol(total_cases)

pop <- d %>% 
    distinct(country, pop) %>% 
    .$pop

stan_data <- list(
    N_days = N_days,
    N_countries = N_countries,
    total_cases = total_cases,
    pop = pop
)

str(stan_data)
```


# About the model

Let $I_{t, i}$ be the total number of diagnosed infected cases in country $i$ at time $t$. Then we write

$$
\begin{aligned}
I_{t, i} &\sim \mathrm{Poisson}(\beta_{t, i} \cdot I_{t - 1, i}) \\
\log(\beta_{t, i}) &\sim \mathrm{Normal}(\log(\beta_{t-1, i}) + \theta_i, \sigma_\varepsilon^2) \\
\beta_{1, i} &\sim \mathrm{Normal}(\mu_\beta, \sigma^2_\beta) \\
\theta_i &\sim \mathrm{Normal}(\mu_\theta, \sigma^2_\theta)
\end{aligned}
$$

```{r}
m <- sampling(stan_model("State_Space.stan"), 
              data  = stan_data, chains = 4, iter = 2000, warmup = 1000)
```

```{r}
tidyMCMC(m, pars = c("beta", "change", "kappa", "alpha"), conf.int = T) %>% 
    mutate(par = str_match(term, "[a-zA-Z]+"),
           term = parse_number(term)) %>% 
    filter(par == "change") %>% 
    mutate(country = factor(term, labels = colnames(total_cases)) %>% fct_reorder(estimate)) %>% 
    mutate_at(vars(estimate, contains("conf")), ~ exp(2.42 * .) - 1) %>% 
    ggplot(aes(country, estimate, ymin = conf.low, ymax = conf.high, group = country)) +
    geom_linerange() +
    geom_point() +
    scale_y_continuous(labels = percent) +
    facet_wrap("par", scales = "free_x") +
    coord_flip()
```



```{r}
chosen <- which(colnames(total_cases) == "Iceland")
tidyMCMC(m, conf.int = T, rhat = T, ess = T) %>% 
    mutate_at(vars(estimate, contains("conf")), ~exp(.) - 1) %>% 
    mutate(par = str_match(term, "[a-zA-Z_2]+")) %>% 
    filter(par == "beta") %>% 
    mutate(day = str_match(term, "([0-9]+),")[, 2] %>% parse_number,
           date = day - 1 + min(d$date),
           country = str_match(term, ",([0-9]+)")[, 2]) %>% 
    ggplot(aes(date, estimate, group = country, 
               col = country == chosen,
               size = country == chosen)) +
    geom_line() +
    scale_y_log10(labels = percent) +
    scale_colour_manual(values = c("grey", "blue")) +
    scale_size_manual(values = c(0.6, 1.3)) +
    theme(legend.position = "none")
```

```{r}
tidyMCMC(m, conf.int = T, rhat = T, ess = T) %>% 
    mutate_at(vars(estimate, contains("conf")), ~ exp(.) - 1) %>% 
    mutate(par = str_match(term, "[a-zA-Z_2]+")) %>% 
    filter(par == "trend_beta") %>% 
    mutate(country = row_number(),
           country = factor(country, labels = colnames(total_cases)),
           country = fct_reorder(country, estimate)) %>% 
    ggplot(aes(country, estimate, group = country, col = country == "Iceland")) +
    geom_point(size = 2) +
    scale_colour_manual(values = c("grey", "blue")) +
    coord_flip() +
    theme(legend.position = "none")
```