---
title: "Logistic"
author: "Brynjólfur Gauti Jónsson"
date: "3/17/2020"
output: 
    html_document:
        theme: flatly
        code_folding: hide
---

```{r setup, context = "setup", include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, 
                      fig.asp = 0.621, out.width = "100%", fig.width = 8)

library(tidyverse); library(knitr); library(kableExtra); library(broom); library(cowplot); 
library(rstan); library(tidybayes); library(scales); library(shinystan)

theme_set(theme_classic(base_size = 12) + 
            background_grid(color.major = "grey90", 
                            color.minor = "grey95", 
                            minor = "xy", major = "xy") +
            theme(legend.position = "none"))
options(mc.cores = parallel::detectCores())
```


# Gögn

## Lönd

```{r, context = "data"}
d <- read_csv("https://www.dropbox.com/s/rn1p592hjazvra6/stan_dat.csv?dl=1") %>% 
  filter(country == "Iceland")
```


## Breytur

```{r}
N_obs <- nrow(d)

days <- d$days
cases <- d$cases


pop <- d %>% distinct(country_id, pop) %>% arrange(country_id) %>%  .$pop


stan_data <- list(N_obs = N_obs, days = days, obs_cases = cases, pop = pop, a = 30, b = 1000)
```

```{r}
str(stan_data)
```



```{r, eval = F}
m <- sampling(stan_model("Hierarchical_Logistic_Cases_Island.stan"), 
              data  = stan_data, chains = 4, iter = 4000, warmup = 2000)
m_ice <- m
# write_rds(m, "Hierarchical_Logistic_Rates.rds")
```

```{r}
tidyMCMC(m, conf.int = T, rhat = T, ess = T) %>% 
  arrange(desc(rhat))
```


```{r}
results <- spread_draws(m, 
             alpha,
             beta, 
             maximum) %>% 
  distinct(alpha, beta, maximum) %>% 
  mutate(iter = row_number()) %>% 
  expand_grid(days = seq(0, 60)) %>% 
  mutate(linear = alpha + beta * days,
         rate = maximum / (1 + exp(-linear)),
         cases = rpois(n(), lambda = rate * 364260)) %>% 
  group_by(days) %>% 
  summarise(median = median(cases),
            upper = quantile(cases, 0.975),
            lower = quantile(cases, 0.025)) %>% 
  mutate(date = days + min(plot_dat$date))

p_cumul <- results %>% 
  ggplot(aes(date, median, ymin = lower, ymax = upper)) +
  geom_line(aes(y = lower), lty = 2) +
  geom_line(aes(y = upper), lty = 2) +
  geom_line() +
  geom_point(data = d,
             aes(date, cases), inherit.aes = F) +
  scale_y_continuous(breaks = pretty_breaks(10)) +
  theme(axis.title.x = element_blank())
p_cumul +
  ggsave("uppsafnad_smit_island.png")
p_cumul
```

```{r}
input <- list(country = "Iceland")
plot_dat <- d %>% filter(country == input$country)
country_id = unique(plot_dat$country_id)
chosen_country <- country_id
results <- spread_draws(m, 
             alpha[country_id],
             beta[country_id], 
             maximum[country_id]) %>% 
  ungroup %>% 
  filter(country_id == chosen_country) %>% 
  distinct(alpha, beta, maximum) %>% 
  mutate(iter = row_number()) %>% 
  expand_grid(days = seq(0, 60)) %>% 
  mutate(linear = alpha + beta * days,
         rate = maximum / (1 + exp(-linear)),
         cases = rpois(n(), lambda = rate * 364260)) %>% 
  group_by(iter) %>% 
  mutate(cases = cases - lag(cases, n = 21, default = 0)) %>% 
  group_by(days) %>% 
  summarise(median = median(cases),
            upper = quantile(cases, 0.975),
            lower = quantile(cases, 0.025)) %>% 
  mutate(date = days + min(plot_dat$date))

p_active <- results %>% 
  ggplot(aes(date, median, ymin = lower, ymax = upper)) +
  geom_line(aes(y = lower), lty = 2) +
  geom_line(aes(y = upper), lty = 2) +
  geom_line() +
  geom_point(data = plot_dat,
             aes(date, cases), inherit.aes = F) +
  theme(axis.title.x = element_blank())

p_active
```

```{r}
results %>% 
  group_by(iter) %>% 
  mutate(healthy = lag(cases, n = 21, default = 0),
         current = cases - healthy) %>% 
  group_by(days) %>% 
  summarise(median = median(current),
            lower = quantile(current, 0.025),
            upper = quantile(current, 0.975)) %>% 
  ggplot(aes(days, median)) +
  geom_line() +
  geom_line(aes(y =  upper), lty = 2) +
  geom_point(data = d %>% filter(country == "Iceland"), aes(x = days, y = cases))
```

