---
title: "Logistic"
author: "Brynjólfur Gauti Jónsson"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.asp = 0.621, out.width = "100%", fig.width = 8)
```

```{r}
packages <- c("tidyverse", "knitr", "kableExtra", "broom", "cowplot", "rstan", "tidybayes", "scales", "ggridges", "lubridate")
installed <- sapply(packages, require, character.only = TRUE, quietly = TRUE)
theme_set(theme_classic(base_size = 12) + 
              background_grid(color.major = "grey90", 
                              color.minor = "grey95", 
                              minor = "xy", major = "xy") +
              theme(legend.position = "none"))
rm(packages, installed)
options(mc.cores = parallel::detectCores())
```


# Case rate

```{r}
d <- read_csv("../../Data/ECDC_Data.csv") %>% 
    filter(country %in% c("Iceland", "South Korea", "China", "Norway", 
                          "Italy", "Denmark", "Sweden", "Switzerland", "Austria",
                          "New Zealand", "Spain", "France", "Japan", "United Kingdom",
                          "Germany", "Belgium", "Austria", "Finland")) %>%
    filter(case_rate > 0.03 | cases > 50) %>% 
    select(country, pop, date, days, cases = cum_cases, case_rate) %>% 
    group_by(country) %>% 
    mutate(days = row_number() - 1) %>% 
    ungroup %>% 
    mutate(country_id = as.numeric(as.factor(country)))
d %>% 
    count(country, sort = T)
```

```{r}
N_obs <- nrow(d)
N_countries <- max(d$country_id)
max_case_rate <- 20


days <- d$days
case_rate <- d$case_rate
cases <- d$cases
country <- d$country_id %>% as.integer


pop <- d %>% distinct(country_id, pop) %>% .$pop
country_max <- d %>% 
    group_by(country_id) %>% 
    summarise(maximum = max(case_rate)) %>% 
    arrange(country_id) %>% 
    .$maximum

country_max_cases <- d %>% 
    group_by(country_id) %>% 
    summarise(maximum = max(cases)) %>% 
    arrange(country_id) %>% 
    .$maximum

country_min_case_rate <- d %>% 
    group_by(country_id) %>% 
    summarise(minimum = min(case_rate)) %>% 
    arrange(country_id) %>% 
    .$minimum
country_n_days <- d %>% 
    count(country_id) %>% 
    .$n

beta_scale <- 10^(floor(log(pop, base = 10))) - 1

stan_data <- list(N_obs = N_obs, N_countries = N_countries, max_case_rate = max_case_rate, beta_scale = beta_scale,
                  days = days, case_rate = case_rate, cases = cases,country = country, 
                  pop = pop, country_max = country_max, country_max_cases = country_max_cases, 
                  country_min_case_rate = country_min_case_rate, country_n_days = country_n_days)
str(stan_data)
```

```{r}
if (!file.exists("Logistic_case_rate.rds")) {
    m <- sampling(stan_model("Logistic_case_rate.stan"), 
                  data  = stan_data, chains = 4, iter = 1000, warmup = 500)
    write_rds(m, "Logistic_case_rate.rds")
} else {
    m <- read_rds("Logistic_case_rate.rds")
}
```


## Saturation

```{r}
tidyMCMC(m, pars = "maximum", conf.int = T, ess = T, rhat = T, estimate.method = "mean") %>% 
    mutate(country_id = row_number()) %>% 
    inner_join(d %>% distinct(country, country_id)) %>% 
    mutate(country = fct_reorder(country, estimate)) %>% 
    ggplot(aes(country, estimate, ymin = conf.low, ymax = conf.high, col = country == "Iceland")) +
    geom_point(size = 3) +
    geom_linerange() +
    coord_flip() +
    scale_colour_manual(values = c("grey30", "blue")) +
    labs(title = "Saturation amount",
         subtitle = "Shown as cases per 1000") +
    scale_y_log10()
```

```{r}
tidyMCMC(m, pars = "beta", conf.int = T, ess = T, rhat = T) %>% 
    mutate(country_id = row_number()) %>% 
    inner_join(d %>% distinct(country, country_id)) %>% 
    mutate(country = fct_reorder(country, estimate)) %>% 
    ggplot(aes(country, estimate, ymin = conf.low, ymax = conf.high, col = country == "Iceland")) +
    geom_point(size = 3) +
    geom_linerange() +
    coord_flip() +
    scale_colour_manual(values = c("grey30", "blue")) +
    labs(title = "Saturation amount",
         subtitle = "Shown as cases per 1000")
```

## Predictions

```{r}
countries = c("Iceland", "Denmark", "Austria",
              "Switzerland", "New Zealand"s)
tidyMCMC(m, pars = c("beta", "maximum"), ess = T, rhat = T) %>% 
    mutate(par = str_replace(term, "\\[.*\\]$", "")) %>% 
    group_by(par) %>% 
    mutate(country_id = row_number()) %>% 
    ungroup %>% 
    inner_join(d %>% group_by(country, country_id) %>% 
                   summarise(date = min(date),
                             min_case_rate = min(case_rate))) %>% 
    filter(country %in% countries) %>% 
    select(country, par, estimate, min_case_rate, date) %>% 
    spread(par, estimate) %>% 
    expand_grid(days = seq(0, 50)) %>% 
    mutate(intercept = log(min_case_rate / (maximum - min_case_rate)),
           linear = intercept + beta * days,
           case_rate = maximum * exp(linear) / (1 + exp(linear)),
           date = date + days) %>% 
    ggplot(aes(date, case_rate, group = country, col = country == "Iceland")) +
    geom_line() +
    geom_point(data = d %>% filter(country %in% countries),
               aes(x = date, y = case_rate)) +
    scale_colour_manual(values = c("grey", "blue"))
```

```{r}
countries = c("Italy")
tidyMCMC(m, pars = c("beta", "maximum"), ess = T, rhat = T) %>% 
    mutate(par = str_replace(term, "\\[.*\\]$", "")) %>% 
    group_by(par) %>% 
    mutate(country_id = row_number()) %>% 
    ungroup %>% 
    inner_join(d %>% group_by(country, country_id) %>% 
                   summarise(date = min(date),
                             min_case_rate = min(case_rate))) %>% 
    filter(country %in% countries) %>% 
    select(country, par, estimate, min_case_rate, date) %>% 
    spread(par, estimate) %>% 
    expand_grid(days = seq(0, 50)) %>% 
    mutate(intercept = log(min_case_rate / (maximum - min_case_rate)),
           linear = intercept + beta * days,
           case_rate = maximum * exp(linear) / (1 + exp(linear)),
           date = date + days) %>% 
    ggplot(aes(date, case_rate, group = country, col = country == "Iceland")) +
    geom_line() +
    geom_point(data = d %>% filter(country %in% countries),
               aes(x = date, y = case_rate)) +
    scale_colour_manual(values = c("grey", "blue"))
```

# Infected

```{r}
d <- read_csv("../../Data/ECDC_Data.csv") %>% 
    filter(continent %in% "Europe") %>%
    select(country, pop, date, days, cases = cum_cases, case_rate) %>% 
    group_by(country) %>% 
    mutate(days = row_number() - 1) %>% 
    ungroup %>% 
    mutate(country_id = as.numeric(as.factor(country)))
```

```{r}
N_obs <- nrow(d)
N_countries <- max(d$country_id)
days <- d$days
cases <- d$cases
country <- d$country_id %>% as.integer
pop <- d %>% distinct(country_id, pop) %>% .$pop
country_max <- d %>% 
    group_by(country_id) %>% 
    summarise(maximum = max(cases)) %>% 
    arrange(country_id) %>% 
    .$maximum
country_min <- d %>% 
    group_by(country_id) %>% 
    summarise(minimum = min(cases)) %>% 
    arrange(country_id) %>% 
    .$minimum

stan_data <- list(N_obs = N_obs, N_countries = N_countries, 
                  days = days, cases = cases, country = country, 
                  pop = pop, country_max = country_max, country_min = country_min)
str(stan_data)
```

```{r}
if (!file.exists("Logistic.stan")) {
    m <- sampling(stan_model("Logistic_cases.stan"), 
                  data  = stan_data, chains = 8, iter = 1000, warmup = 500)
    write_rds(m, "Logistic_cases.rds")
} else {
    m <- read_rds("Logistic_cases.rds")
}
```

```{r}
tidyMCMC(m, rhat = T, ess = T)
```


```{r}
tidyMCMC(m, pars = "maximum", conf.int = T, ess = T, rhat = T, estimate.method = "mean") %>% 
    mutate(country_id = row_number()) %>% 
    inner_join(d %>% distinct(country, country_id)) %>% 
    mutate(country = fct_reorder(country, estimate)) %>% 
    select(country, estimate, conf.low, conf.high, rhat, ess)
```

## Saturation

```{r}
tidyMCMC(m, pars = "maximum", conf.int = T, ess = T, rhat = T) %>% 
    mutate(country_id = row_number()) %>% 
    inner_join(d %>% distinct(country, country_id)) %>% 
    mutate(country = fct_reorder(country, estimate)) %>% 
    filter(estimate <= 1e6) %>% 
    ggplot(aes(country, estimate, ymin = conf.low, ymax = conf.high)) +
    geom_linerange()  +
    geom_point() +
    coord_flip() +
    labs(title = "Saturation amount",
         subtitle = "Shown as cases per 1000")
```

## Predictions

```{r}
countries <- "South Korea"
tidyMCMC(m, pars = c("beta", "maximum"), ess = T, rhat = T) %>% 
    mutate(par = str_replace(term, "\\[.*\\]$", "")) %>% 
    group_by(par) %>% 
    mutate(country_id = row_number()) %>% 
    ungroup %>% 
    inner_join(d %>% 
                   group_by(country, country_id) %>% 
                   summarise(date = min(date),
                             min_cases = min(cases))) %>%
    filter(country %in% countries) %>% 
    select(country, par, estimate, min_cases, date) %>% 
    spread(par, estimate) %>% 
    expand_grid(days = seq(0, 30)) %>% 
    mutate(intercept = log(min_cases / (maximum - min_cases)),
           linear = intercept + beta * days,
           cases = maximum * exp(linear) / (1 + exp(linear)),
           date = date + days) %>% 
    ggplot(aes(date, cases, group = country)) +
    geom_line() +
    geom_point(data = d %>% filter(country %in% countries), aes(x = date, y = cases), inherit.aes = F) +
    scale_colour_manual(values = c("grey", "blue"))
```